SET SERVEROUTPUT ON;
ALTER TABLE ARTICULOS DROP (ASTERISCOS);
ALTER TABLE ARTICULOS ADD (ASTERISCOS NUMBER(10));
DECLARE
	CODIGO VARCHAR2(8);
	PRECIO NUMBER(22);
	ASTERISKOS NUMBER(10);
BEGIN
	CODIGO:=&CODIGO;
	PRECIO:=&PRECIO;
	ASTERISKOS:=PRECIO/20;
	INSERT INTO ARTICULOS (CODA,NOMBRE,PVP,COLOR,CTD,IVA,ASTERISCOS)VALUES(CODIGO,NULL,PRECIO,NULL,NULL,NULL,ASTERISKOS);
	DBMS_OUTPUT.PUT_LINE('SE HAN AÑADIDO '||ASTERISKOS||' ASTERISCOS');
END;    