DECLARE
	CURSOR PERSONASS IS SELECT * FROM PERSONAS;
	PERSONA PERSONAS%ROWTYPE;
	ANADIDO NUMBER(2);
	EXCEPCIONEDAD EXCEPTION;
BEGIN
    SAVEPOINT UNO;
	FOR PERSONA IN PERSONASS LOOP
		ANADIDO:=(PERSONA.EDAD+2);
		IF (ANADIDO<16 OR ANADIDO>65) THEN
            	RAISE EXCEPCIONEDAD;
        END IF;
		DBMS_OUTPUT.PUT_LINE('LA EDAD ORIGINAL ES: '|| PERSONA.EDAD ||' LA MODIFICADA '||ANADIDO);
		UPDATE PERSONAS SET EDAD=ANADIDO;
	END LOOP;
EXCEPTION
    WHEN EXCEPCIONEDAD THEN
    	DBMS_OUTPUT.PUT_LINE('SQLCODE: '||SQLCODE||' EDAD SOBREPASA EL LÍMITE');
		ROLLBACK TO UNO;
	WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('OTRO ERROR HA OCURRIDO');
END;