CREATE OR REPLACE PROCEDURE SUMAR(num_limite NUMBER)
IS
BEGIN
    FOR I IN 0..num_limite LOOP
    	DBMS_OUTPUT.PUT_LINE('EL NUMERO SELECCIONADO ES: '||I);
	END LOOP;
END;
/
DECLARE
BEGIN
	SUMAR(25);
END;