--CON WHILE
DECLARE
    CURSOR CLIENTESS IS SELECT * FROM CLIENTES;
    CLIENTE CLIENTES%ROWTYPE;
BEGIN
    OPEN CLIENTESS;
    FETCH CLIENTESS INTO CLIENTE;
        WHILE (CLIENTESS%FOUND) LOOP
	        DBMS_OUTPUT.PUT_LINE('EL CODIGO ES '||CLIENTE.CODC||', EL NOMBRE: '||CLIENTE.NOMBRE||' Y EL TELEFONO: '||CLIENTE.TLF);
	        FETCH CLIENTESS INTO CLIENTE;
        END LOOP;
    CLOSE CLIENTESS;
END;

--CON FOR
DECLARE
	CURSOR CLIENTESS IS SELECT * FROM CLIENTES;
	CLIENTE CLIENTES%ROWTYPE;
BEGIN
	FOR CLIENTE IN CLIENTESS LOOP
		DBMS_OUTPUT.PUT_LINE('EL CODIGO ES '||CLIENTE.CODC||', EL NOMBRE: '||CLIENTE.NOMBRE||' Y EL TELEFONO: '||CLIENTE.TLF);
	END LOOP;
END;

--CON WHILE
DECLARE
	CURSOR CLIENTESS IS SELECT * FROM CLIENTES;
	CLIENTE CLIENTES%ROWTYPE;
BEGIN 
	OPEN CLIENTESS;
	FETCH CLIENTESS INTO CLIENTE;
	WHILE(CLIENTESS%FOUND) LOOP
        DBMS_OUTPUT.PUT_LINE('EL CODIGO ES '||CLIENTE.CODC||', EL NOMBRE: '||CLIENTE.NOMBRE||' Y EL TELEFONO: '||CLIENTE.TLF);
	END LOOP;
	CLOSE CLIENTESS;
END;