CREATE OR REPLACE PROCEDURE INSERTAR_ARTICULO(CODIGO ARTICULOS.CODA%TYPE,NOMBRE ARTICULOS.NOMBRE%TYPE,PVP ARTICULOS.PVP%TYPE,COLOR ARTICULOS.COLOR%TYPE,CTD ARTICULOS.CTD%TYPE, IVA ARTICULOS.IVA%TYPE)
IS
BEGIN
	INSERT INTO ARTICULOS VALUES(CODIGO,NOMBRE,PVP,COLOR,CTD,IVA);
END;
/
BEGIN
	INSERTAR_ARTICULO('1D5S','HECTOR','45','AMARILLO',45,21);
	DBMS_OUTPUT.PUT_LINE('INSERCCIÓN CORRECTA');
END;