CREATE OR REPLACE FUNCTION DESCRIPCION(CODIGO ARTICULOS.CODA%TYPE)
RETURN VARCHAR
IS
	ARTICULO ARTICULOS%ROWTYPE;
BEGIN
	SELECT * INTO ARTICULO FROM ARTICULOS WHERE CODA=CODIGO;
	RETURN('CODIGO: '||ARTICULO.CODA||' NOMBRE: '||ARTICULO.NOMBRE||' PVP: '||ARTICULO.PVP||' COLOR: '||ARTICULO.COLOR||' CTD: '||ARTICULO.CTD||' IVA: '||ARTICULO.IVA);
END;
/
BEGIN
	DBMS_OUTPUT.PUT_LINE(DESCRIPCION('A2'));
END;