DECLARE 
	EXCEPCIONEDAD EXCEPTION;
	NUM_VIEJOS NUMBER(2);
	CURSOR PERSONASS IS SELECT * FROM PERSONAS;
	PERSONA PERSONAS%ROWTYPE;
	COMPROBANTE NUMBER(4,2);
BEGIN
	FOR PERSONA IN PERSONASS LOOP
		IF PERSONA.EDAD >60 THEN
			NUM_VIEJOS:=NUM_VIEJOS+1;
		END IF;
	END LOOP;
	COMPROBANTE:=NUM_VIEJOS/2;
	IF (COMPROBANTE =>2) THEN
        RAISE EXCEPCIONEDAD;
	END IF;
EXCEPTION
    WHEN EXCEPCIONEDAD THEN
    	DBMS_OUTPUT.PUT_LINE('POBLACIÓN ENVEJECIDA');
	WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('OTRO ERROR');
END;

