DECLARE
	CURSOR CLIENTESS IS SELECT * FROM CLIENTES WHERE TLF='1%';
	CLIENTE CLIENTE%ROWTYPE;
BEGIN
	FOR CLIENTE IN CLIENTESS LOOP
    	DBMS_OUTPUT.PUT_LINE('EL CODIGO ES '||CLIENTE.CODC||', EL NOMBRE: '||CLIENTE.NOMBRE||' Y EL TELEFONO: '||CLIENTE.TLF);
	END LOOP;
END;