CREATE OR REPLACE FUNCTION MULTIPLOS(NUMERO1 NUMBER,NUMERO2 NUMBER)
RETURN BOOLEAN
IS
BEGIN
    IF NUMERO2=0 THEN
    	RETURN FALSE;
	END IF;
	IF MOD(NUMERO1,NUMERO2)=0 THEN
        RETURN TRUE;
	ELSE
        RETURN FALSE;
	END IF;
END;
/
BEGIN
    IF MULTIPLOS(9, 4) THEN
        DBMS_OUTPUT.PUT_LINE('TRUE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('FALSE');
    END IF;
END;