SET SERVEROUTPUT ON;
--He puesto para que el usuario introduzca el dato(&DNI_CLIENTE) pero en LiveSQL no funciona, hay que usar cualquier valor
DECLARE
	DNI_CLIENTE VARCHAR2(10);
	NUMERO_FACTURAS NUMBER(2);
	SUMA_FACTURAS NUMBER(8,2);
BEGIN
    -- DNI CLIENTE
    DNI_CLIENTE:=&DNI_CLIENTE;
	DBMS_OUTPUT.PUT_LINE('EL DNI ELIMINADO ES '||DNI_CLIENTE);
    -- CONTEO FACTURAS
    SELECT count(*) INTO NUMERO_FACTURAS 
    FROM FACTURAS 
    INNER JOIN CLIENTES ON CLIENTES.CODC = FACTURAS.CODC 
    WHERE CLIENTES.DNI=DNI_CLIENTE;
	-- Suma del precio
	SELECT sum(PRECIO) INTO SUMA_FACTURAS
    FROM FACTURAS
    INNER JOIN CLIENTES ON CLIENTES.CODC = FACTURAS.CODC
    WHERE CLIENTES.DNI=DNI_CLIENTE;
	DBMS_OUTPUT.PUT_LINE('El número de facturas con el dni: '||DNI_CLIENTE||' es '||NUMERO_FACTURAS||' y la suma de ellas es de: '|| SUMA_FACTURAS ||'€');
END;
