CREATE OR REPLACE PROCEDURE BORRADO_ARTICULO(CODIGO ARTICULOS.CODA%TYPE)
IS
BEGIN
	DELETE FROM ARTICULOS WHERE CODA=CODIGO;
	DBMS_OUTPUT.PUT_LINE('ELIMINACION DE ARTICULO CORRECTA');
END;
/
BEGIN
	CAMBIO_NOMBRE('A1');
END;