SET SERVEROUTPUT ON;
--He puesto para que el usuario introduzca el dato (&PAIS_PROVEEDOR)pero en LiveSQL no funciona, hay que usar cualquier valor
DECLARE
	PAIS_PROVEEDOR VARCHAR(20);
	NUMERO_PAISES NUMBER(2);
BEGIN
    PAIS_PROVEEDOR:=&PAIS_PROVEEDOR;
	SELECT COUNT(*) INTO NUMERO_PAISES FROM PROVEEDORES WHERE PAIS=PAIS_PROVEEDOR;
	DBMS_OUTPUT.PUT_LINE('El número de paises eliminados es de: '|| NUMERO_PAISES);
	DELETE FROM PROVEEDORES WHERE PAIS=PAIS_PROVEEDOR;
END;