CREATE OR REPLACE PROCEDURE CAMBIO_NOMBRE(NOMBRE_NUEVO ARTICULOS.NOMBRE%TYPE)
IS
    CODIGO_ARTICULO ARTICULOS.CODA%TYPE;
BEGIN
    CODIGO_ARTICULO:='A1';
	UPDATE ARTICULOS SET NOMBRE=NOMBRE_NUEVO WHERE CODA=CODIGO_ARTICULO;
	DBMS_OUTPUT.PUT_LINE('CAMBIO DE NOMBRE CORRECTO');
END;
/
BEGIN
	CAMBIO_NOMBRE('LOPARDO');
END;