SET SERVEROUTPUT ON;

DROP TABLE MENSAJES;
CREATE TABLE MENSAJES(
    VALOR VARCHAR2(5)
);

DECLARE
	VALOR2 VARCHAR(5);
BEGIN
	FOR i IN 1..10 LOOP
		IF i NOT IN(4,5)THEN
			DBMS_OUTPUT.PUT_LINE('EL NUMERO AÑADIDO ES ' || i);
			VALOR2 := TO_CHAR(i);
			INSERT INTO MENSAJES VALUES(VALOR2);
		END IF;
	END LOOP;
END;