CREATE OR REPLACE FUNCTION DEVOLVERMAYOR(NUMERO1 NUMBER,NUMERO2 NUMBER)
RETURN NUMBER
IS
	NUMEROMAYOR NUMBER;
BEGIN
	IF NUMERO1<NUMERO2 THEN
		NUMEROMAYOR:=NUMERO2;
	ELSE
		NUMEROMAYOR:=NUMERO1;
	END IF;
	RETURN(NUMEROMAYOR);
END;
/
BEGIN
	DBMS_OUTPUT.PUT_LINE('EL NUMERO MAYOR ES '||DEVOLVERMAYOR(8,78));
END;