CREATE OR REPLACE PROCEDURE DIVIDIRNUMEROS(DIVIDENDO NUMBER,DIVISOR NUMBER)
IS
    DIVISION NUMBER(4,2);
	CERO EXCEPTION;
BEGIN
	IF DIVISOR=0 THEN
        RAISE CERO;
	END IF;
	DIVISION:=DIVIDENDO/DIVISOR;
	DBMS_OUTPUT.PUT_LINE('EL RESULTADO DE LA DIVISION ES: '||DIVISION);
EXCEPTION
    WHEN CERO THEN
    	DBMS_OUTPUT.PUT_LINE('NO SE PUEDE DIVIDIR ENTRE 0');
END;
/
BEGIN
	DIVIDIRNUMEROS(7,0);
END;